{% set name = "verible" %}
{% set version = "0.0-3999-g93adb37c" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - url: https://github.com/chipsalliance/verible/releases/download/v{{ version }}/verible-v{{ version }}-linux-static-x86_64.tar.gz  # [linux and x86_64]
    sha256: f5683304432672aaa8cf3bb78b6b0958869d8baad15b70f44c1ea94c4e4c968d  # [linux and x86_64]
  - url: https://github.com/chipsalliance/verible/releases/download/v{{ version }}/verible-v{{ version }}-linux-static-arm64.tar.gz  # [linux and aarch64]
    sha256: 58ceb07b07b2f14d7f1ca16ecb30d90cc54511f9e248bd7357cffd7a307e301c  # [linux and aarch64]
  - url: https://github.com/chipsalliance/verible/releases/download/v{{ version }}/verible-v{{ version }}-macOS.tar.gz  # [osx and aarch64]
    sha256: fc1b00e0f558d2f6762d9d98786b95e0b8b875453e18401b78cec4ac6542a956  # [osx and aarch64]

build:
  number: 0
  skip: true  # [win or (osx and x86_64)]

requirements:
  build:
    # No build requirements needed for binary distribution
  host:
    # No host requirements needed for binary distribution
  run:
    # Static binaries don't need runtime dependencies
    # but conda-forge may require some basic ones
    - __glibc >=2.17  # [linux]

test:
  commands:
    - verible-verilog-lint --version
    - verible-verilog-diff --version
    - verible-verilog-format --version
    - verible-verilog-syntax --version

about:
  home: https://github.com/chipsalliance/verible
  summary: |
      The Verible project's main mission is to parse SystemVerilog (IEEE 1800-2017)
      (as standardized in the SV-LRM) for a wide variety of applications, including
      developer tools.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
