schema_version: 1

context:
  name: verible
  version: 0.0-3667-g88d12889

package:
  name: ${{ name|lower }}
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/chipsalliance/verible/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6a13a902bfd37ecabfd772d619251da40e8ad8e44cf75ec2bc8663046200b02a
  patches:
    - build_opts_patch.patch

build:
  number: 1
  skip: win

requirements:
  build:
    - bazel >=5,<=7
    - bazel-toolchain
    - flex
    - bison
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - patchelf

tests:
  - script:
      - verible-verilog-lint --version
      - verible-verilog-diff --version

about:
  summary: |
    The Verible project's main mission is to parse SystemVerilog (IEEE 1800-2017)
    (as standardized in the SV-LRM) for a wide variety of applications, including
    developer tools.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/chipsalliance/verible

extra:
  recipe-maintainers:
    - dillonroach
